### 1. Write a Python Program to Add Two Matrices?

Program Steps:-
- The program that we are going to discuss next will follow the below-mentioned sequence:

- Ask the user to enter the number of rows and columns for the matrices to be added.
- Now, use the list comprehension and input() function to ask the user to enter the elements for both the matrices.
- Create a result matrix with the same dimension of both the matrices and keep its all element as 0.
- Using the Nested for loop, add the element of the first matrix with the other and store the result in the result matrix.
- Display the output.

In [2]:
#matrix addition in python
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_a:
    print(n)

print("Enter the elements of Second Matrix:")
matrix_b= [[int(input()) for i in range(column)] for i in range(rows)]
for n in matrix_b:
    print(n)
    
result=[[0 for i in range(column)] for i in range(rows)]

for i in range(rows):
    for j in range(column):
        result[i][j] = matrix_a[i][j]+matrix_b[i][j]

print("The Sum of Above two Matrices is : ")
for r in result:
    print(r)


Enter the Number of rows : 3
Enter the Number of Columns: 3
Enter the elements of First Matrix:
1
2
3
4
5
6
7
8
9
First Matrix is: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Enter the elements of Second Matrix:
1
2
3
4
5
6
7
8
9
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
The Sum of Above two Matrices is : 
[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


##### Matrix Addition in Python using Numpy
Numpy is a popular Python library that is famous for its arrays and matrix operations. In the above section, we learned how to add two matrices in Python using the nested for loop. Now let’s discuss how can we use a numpy library and perform the same matrix addition in Python.

Note: To use the numpy library we first need to install it. To install the numpy library for our Python environment we can use the pip install numpy command.

Example: Addition of two matrices in Python using numpy add method
Similar to the above program we first accept the user input matrix as a list, convert it into the Python numpy matrix using numpy array() method and then perform the addition operation.

In [3]:
import numpy as np

#matrix addition in python using numpy
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

#accept the first matix
print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_a:
    print(n)

#convert the first matrix into numpy array
matrix_a = np.array(matrix_a)

#accept the second matix
print("Enter the elements of Second Matrix:")
matrix_b= [[int(input()) for i in range(column)] for i in range(rows)]
for n in matrix_b:
    print(n)
    
#convert the second matrix into numpy array
matrix_b = np.array(matrix_b)    

#add two matrices in python using numpy
result = np.add(matrix_a, matrix_b)

print("The Sum of Above two Matrices is : ")
for r in result:
    print(r)

Enter the Number of rows : 3
Enter the Number of Columns: 3
Enter the elements of First Matrix:
3
3
3
3
3
3
3
3
3
First Matrix is: 
[3, 3, 3]
[3, 3, 3]
[3, 3, 3]
Enter the elements of Second Matrix:
3
3
3
3
3
3
3
3
3
[3, 3, 3]
[3, 3, 3]
[3, 3, 3]
The Sum of Above two Matrices is : 
[6 6 6]
[6 6 6]
[6 6 6]


### 2. Write a Python Program to Multiply Two Matrices?

Steps to Multiply Two Matrices in Python

- Ask the user to enter the number of rows and columns for the first matrix.
- Enter the elements for the first matrix.
- Now ask the user to enter only the number of columns for the second matrix because the rows of the second matrix should be equal to the columns of the first matrix.
- Enter the elements for the second matrix.
- Use a nested loop inside a loop and perform the logic, result [i][j]+=matrix_a[i][k]*matrix_b[k][j].

In [4]:
rows_a = int(input("Enter the Number of rows  for the first matrix: " ))
column_a = int(input("Enter the Number of Columns for the first matrix: "))

print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column_a)] for i in range(rows_a)]

print("First Matrix is: ")
for n in matrix_a:
    print(n)
#the number of columns of first matrix is equal to the number of rows of second matrix
column_b = int(input("Enter the Number of Columns for the second matrix: "))

print("Enter the elements of Second Matrix:")

matrix_b= [[int(input()) for i in range(column_b)] for i in range(column_a)]
for n in matrix_b:
    print(n)
    
result=[[0 for i in range(column_b)] for i in range(rows_a)]

for i in range(len(matrix_a)):
    for j in range(len(matrix_b[0])):
        for k in range(len(matrix_b)):
            result [i][j]+=matrix_a[i][k]*matrix_b[k][j]
print("\nMatrix_a X Matrix_b is: ")
for r in result:
    print(r)


Enter the Number of rows  for the first matrix: 2
Enter the Number of Columns for the first matrix: 2
Enter the elements of First Matrix:
2
2
2
2
First Matrix is: 
[2, 2]
[2, 2]
Enter the Number of Columns for the second matrix: 2
Enter the elements of Second Matrix:
2
2
2
2
[2, 2]
[2, 2]

Matrix_a X Matrix_b is: 
[8, 8]
[8, 8]


### 3. Write a Python Program to Transpose a Matrix?

In [7]:
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of Matrix:")
matrix= [[int(input()) for i in range(column)] for i in range(rows)]
print("-------Your  Matrix is---------")
for n in matrix:
    print(n)

#result matrix of column*row  dimension

result =[[0 for i in range(rows)] for j in range(column)]

#transpose the matrix
for r in range(rows):
   
   for c in range(column):
       #here we are grabbing the row data of matrix and putting it in the column on the result
       result[c][r] = matrix[r][c]

print("Transpose matrix is: ")
for r in result:
    print(r)
    
    

Enter the Number of rows : 3
Enter the Number of Columns: 3
Enter the elements of Matrix:
1
2
3
4
5
6
7
8
9
-------Your  Matrix is---------
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Transpose matrix is: 
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

##### Method 1: Using sorted()
sorted() is a predefined function in Python which returns the sorted list of any particular sequence.

In [14]:
# Program to sort alphabetically the words form a string provided by the user

my_str = input("enter string :-")

# To take input from the user
#my_str = input("Enter a string: ")

# breakdown the string into a list of words
words = [word.lower() for word in my_str.split()]

# sort the list
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
   print(word)


enter string :-go ahead , make my day
The sorted words are:
,
ahead
day
go
make
my


### 5. Write a Python Program to Remove Punctuation From a String?

In [20]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "enter the string"

# To take input from the user
# my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)


enter the string
